info:
  name: Delete
  type: http
  seq: 4

http:
  method: DELETE
  url: "{{url}}/auth/roles/6a7ca7d21e6f568206d5d494"
  body:
    type: json
    data: ""
  auth:
    type: bearer
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTdjMTVhMzdjMzllYWQ4YzQxZTIzMDYiLCJwaG9uZSI6IjgxOTk4NTQ4OTgiLCJpYXQiOjE3ODY1NTM3OTgsImV4cCI6MTc4NjU1NDY5OH0.3OLE3zdv9aXPZ_BmbtBpCSkeY1GtEQYVmooX2GZQrok

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
